### ISSUE TITLE
How to disable anonymous health tracking

### ISSUE THREAD

**Issue by amisol** [robocorp/rcc#11]
Since I'm connected to corporate VPN, I'm getting this error when trying to execute my robot 

Installed pip packages:
Error [http.Do]: Put "https://telemetry.robocorp.com/metric-v1/rcc.user/...../rcc.env.create.start/v7.1.5": dial tcp: lookup telemetry.robocorp.com on ..... no such host
Error [http.Do]: Put "https://telemetry.robocorp.com/metric-v1/rcc.user/1.....rcc.cli.run/v7.1.5": dial tcp: lookup telemetry.robocorp.com on.....: no such host

Also when running rcc configure identity I'm seeing and `anonymous health tracking is: enabled`

How do I disable that? 

Thank you

**Comment by vjmp** [comment]
You can disable it using command: `rcc configure identity --do-not-track`

And when you need to enable it, command is: `rcc configure identity --enable`

And as you found out, you can find status by running: `rcc configure identity`

And finally, in general, you can ask rcc for help: `rcc configure identity --help`

Does this resolve your problem?

**Comment by vjmp** [comment]
Closing this, since no additional problem has been reported. And to best of my understanding, above instruction should be enough to resolve  this issue.
