### ISSUE TITLE
Error calling rcc env variables

### ISSUE THREAD

**Issue by fabioz** [robocorp/rcc#12]
RCC version: v9.3.10
OS: Windows 10

When calling:

`rcc.exe env variables -r x:\vscode-robot\local_test\minimal\robot.yaml --controller RobocorpCode`

I'm getting an error saying:

`Variable exporting failed because: open c:\temp\robohome\temp\556dc980f940b574\require_602bb455.txt: The system cannot find the path specified.`

Note that `ROBOCORP_HOME` is set to `c:\temp\robohome` in this case.

**Comment by vjmp** [comment]
Problem probably is, that since `--lease "who did it"` was not used, that temp folder gets recycled on next rcc execution.

If variables request is done with lease, then that temp folder is protected from recyling.
