### ISSUE TITLE
Error [http.Do] net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by shanshouchen** [robocorp/rcc#13]
I got a error message like this:
![image](https://user-images.githubusercontent.com/9147956/108471571-88d9d380-72c6-11eb-9678-19e664a1bac1.png)

**Comment by vjmp** [comment]
Some questions:

1. is this repeatable, or was it just one time issue for you?
2. does/did it prevent your run to complete?
3. do other operations also have this TLS handshake timeout issue?

@shanshouchen if you could answer above things, it could help me get started.

**Comment by kariharju** [comment]
The error looks to point to some proxy settings.

We have a [firewall/proxy guide](https://robocorp.com/docs/troubleshooting/firewall-and-proxies) for what outgoing traffic the tooling requires.

Also with the latest RCC you can run:
`rcc config diagnostics`
..and it checks some basics for the network connectivity.

**Comment by vjmp** [comment]
And I'm going to add "panic" prevention on next rcc, so even if there is probem inside metrics, it should not prevent normal usage. This change will close this issue. If problem persists, create new issue, with more details.
