### ISSUE TITLE
ROBOCORP_HOME misreferenced as ROBOCORP in help text's "Flags" section 

### ISSUE THREAD

**Issue by ottoaho** [robocorp/rcc#18]
If I'm not mistaken, [this line](https://github.com/robocorp/rcc/blob/08a294625a1b347b462041a5c60c48dd53bde398/cmd/root.go#L95) should say:
`rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $ROBOCORP_HOME/rcc.yaml)")`

**Comment by vjmp** [comment]
Thank you. Good catch. Will fix.
