### ISSUE TITLE
How to use credentials for pip index?

### ISSUE THREAD

**Issue by vx-i** [robocorp/rcc#22]
Hi all,

I'm using Azure DevOps Artifacts to provide internal python packages. Artifacts is using keyring and artifacts-keyring package to authenticate or you need to set up extra-index-url with this format:

https://user:pass@pkgs.dev.azure.com/org/project/_packaging/feed/pypi/simple/

This is needed cause rcc is starting pip with option --isolated. It's ignoring environment variables and user configuration. The fact that keyring packages can't be used and pip is made dumb, I need to put index url parameter to conda.yaml. With credentials as clear text. Is there a possibility to make it more secure or more comfortable?

If rcc would use keyring packages to provide Active Directory data, this would be perfect. Otherwise rcc should support environment variables or something similar.

**Comment by kariharju** [comment]
Hi,
At the moment we have the settings.yaml that you could try out to solve your case.
This is a feature we have mostly planned to IT departments so we don't have the documented too widely as of now.
Run `rcc config settings > settings.yaml` and place the output settings.yaml to ROBOCORP_HOME which by default in Windows is `%localappdata%\robocorp` (linux&mac: `~/.robocorp`)

In the settings.yaml you can define the pypi settings.

Re-open if this did not work for you.
Br, Kari

**Comment by vx-i** [comment]
@kariharju Thanks for the hint, but unfortunately it doesn't help. Within settings.yaml you can only replace PyPI with DevOps Artifacts. However, both are needed. Like in pip, index-url and extra-index-url.
