### ISSUE TITLE
rcc man usecases don't work in v11.6.6

### ISSUE THREAD

**Issue by antusystem** [robocorp/rcc#29]
Hi, I was checking a lot of things from `rcc` and in ` v11.6.6 ` if I execute the command `rcc man usecases` it returns this:

`Cannot show usecases.md, reason: Asset docs/usecases.md not found`

I don't know if this was fixed in other version, but this one is the last stable i found. Thanks

**Comment by vjmp** [comment]
This is already fixed in v11.9.12 or there about. Thank you for reporting.

Can be downloaded from: https://downloads.robocorp.com/rcc/releases/index.html
