### ISSUE TITLE
rcc task script command is not working

### ISSUE THREAD

**Issue by adrian-evo** [robocorp/rcc#32]
I tried to run `rcc task script -- pip list` as suggested in the command prompt, but it is not working.  I get the following, when I try to run within image search sample robot:

Error: Could not resolve what task to run. Select one using --task option.
Available task names are: "Image search".

Using both latest Rcc as well as the stable one 11.9.10.

![image](https://user-images.githubusercontent.com/19324942/166901365-81a419b0-0cf8-4d3e-b113-e6b791ed6ef5.png)

**Comment by vjmp** [comment]
Thank you for reporting this. Good finding. It should now be fixed in v11.12.4.
