### ISSUE TITLE
rcc hanging in feedback metric 

### ISSUE THREAD

**Issue by fabioz** [robocorp/rcc#34]
This was reported by a user in: https://forum.robocorp.com/t/rcc-exe-runnng-900x-when-using-vs-code/1760

The actual command line which is leaving rcc processes open is:

`c:\Users\brian\.vscode\extensions\robocorp.robocorp-code-0.32.0\bin\rcc.exe feedback metric -t vscode -n vscode.lsp.error -v HANDLE_DEBUG_SESSION_EVENT`

**Comment by vjmp** [comment]
Closing this, since it was resolved in vscode extension side.
