### ISSUE TITLE
RCC does not support environment variables in robot.yaml

### ISSUE THREAD

**Issue by vx-i** [robocorp/rcc#38]
I would like to use different log folders dependent on environment variables. The command below works well via cmd.exe. But when I run RCC then the environment variables are not resolved. I've searched the documentation but can't find a suitable solution. It looks like it is not supported? If not, are there any plans?

robot.yaml
---
tasks:
  Run Producer:
    command:
    - python
    - -m
    - robot
    - --report
    - NONE
    - --outputdir
    - \\hostname\Logs\Prod\000\Mail_Collector_Switch
    - --output
    - output-%WV_ID%.xml
    - --logtitle
    - "Task log"
    - --loglevel
    - INFO
    - --log
    - log-%WV_ID%.html
    - --timestampoutputs
    - --task
    - Run Producer
    - tasks.robot

condaConfigFile: environment.yaml
artifactsDir: output
PATH:
  - .
PYTHONPATH:
  - keywords
  - keywords_ro
  - variables
  - .
  
ignoreFiles:
  - .gitignore

**Comment by vjmp** [comment]
See this for possible solution for you: https://forum.robocorp.com/t/date-folder-creation-inside-output-folder/2071/2

**Comment by vx-i** [comment]
@vjmp Works perfect. Many thanks.
