### ISSUE TITLE
Build error for buildstats.go: undefined: any

### ISSUE THREAD

**Issue by datakurre** [robocorp/rcc#41]
Once again, this is probably just me, but when building the latest version (v11.34.0) I get the following build errors:

```
go/src/github.com/robocorp/rcc/journal/buildstats.go:361:22: undefined: any
go/src/github.com/robocorp/rcc/journal/buildstats.go:519:36: undefined: any
```

v11.31.2 did still build properly.

Any tips, is that something that could/should be fixed in RCC or is it more probably just me missing something in my build?

**Comment by vjmp** [comment]
Too old go version to build. Upgrade your go language.

**Comment by datakurre** [comment]
Thanks. Confirmed that I was using 1.17.13.

Built fine with 1.18.7.
