### ISSUE TITLE
Name of hololib zip file should be configurable on import

### ISSUE THREAD

**Issue by simonmeggle** [robocorp/rcc#44]
When exporting with `rcc ht export .....`, `--zipfile` allows to specify a custom name for the ZIP file. 
It would be great to specify the file also for import.

**Comment by vjmp** [comment]
You can. It is not behind flag. It is just simple arguments, and could be more than one. Like:
`rcc holotree import one.zip other.zip third.zip more.zip`

Does this work for you, @simonmeggle ?

**Comment by simonmeggle** [comment]
Sorry, I overlooked the "+" sign in the command usage. Yes, works - thanks!
