### ISSUE TITLE
111 Could not read default settings, reason: open assets/settings.yaml: file does not exist

### ISSUE THREAD

**Issue by PaulYuanJ** [robocorp/rcc#49]
Hello there,

I have cloned this project and run it under the environment:

OS: Windows 11
Go Version: go version go1.20.2 windows/amd64   or  go version go1.18.10 windows/amd64

When I try to run:
go run cmd/rcc/main.go

the error appears:
```
Fatal failure with 'C:\Users\123\AppData\Local\robocorp\settings.yaml', see: {111 Could not read default settings, reason: open assets/settings.yaml: file does not exist}
Sorry. Cannot recover, will exit now!
```

**Comment by vjmp** [comment]
It is not expected to be `go run` ... it should be compiled and then run that executable. And easiest way to get access build binaries is to follow instructions on top level README.md and "Getting started" section there.

What is the need for `go run`, can you describe your use-case.

Will close this issue in near future, if no further needs appear.

**Comment by PaulYuanJ** [comment]
I want to compiled it as a service, call http method to create conda env and so on. So I try to run the project from source code.

**Comment by PaulYuanJ** [comment]
I didn't find a README for configuring a local development environment for this project,  do you have one and if it is possible to share it for me ? thank you very very much.

**Comment by kariharju** [comment]
The development of rcc is at the moment heavily done on Linux so we do not have a development guide Windows.

On the use case would be interesting to heard what you goal is? If it is just to provide environment builds via HTTP calls. Maybe the best way would be to just make the http service separately that uses rcc calls in the background.. so I do not see how mixing this inside RCC source codes would help. We use this style in AWS and all our tooling so would be interested to heard if there is some use case we have just missed?

(rcc originally was a service implementation, but we ran into bunch of setup and UX problems "in the realworld" that just keeping it as a executable made much more sense)

**Comment by vjmp** [comment]
And to see how it is build, some hints are at https://github.com/robocorp/rcc/blob/master/docs/BUILD.md doc (which link can also be found on README.md file). And other source for "how to build it" can be found on GHAs at https://github.com/robocorp/rcc/blob/master/.github/workflows/rcc.yaml

**Comment by PaulYuanJ** [comment]
Thank you for your response~

RCC is really a cool tool. I want re-build it as a service and deploy it on my other hosts(worker), you can understand it that I want to make it as a workforce agent to help me manage env and run my robot by service call on my worker.

**Comment by vjmp** [comment]
And are you aware, that we already have lots of that build elsewhere? So instead of building it yourself, just use ready made tooling (which already use rcc as is, that is as CLI tool).

See our documentation at: https://robocorp.com/docs/control-room/unattended/worker-setups

**Comment by PaulYuanJ** [comment]
Thanks vjmp,

I have some special workers, they could not reach internet.

I want to develop a http service based on rcc project to 
* compress and transfer virtual-envs to such wokers off-line if they can only reach intranet.
* install conda env on-line if there worker could reach internet.
* run robots
* ... ...

Thank you for your advice "make the http service separately that uses rcc calls in the background", I think it is a best/easy way to  satify my requirements.

Thank you all very much.

**Comment by vjmp** [comment]
About "compress and transfer", please be aware about holotree export and import. That functionality already should have that covered (except for web hosting part).

And for workers, that are really restricted, use `--no-build` option to make it really sandboxed.
