### ISSUE TITLE
If it is possible to make a progress bar while do "rcc ht import http://xxx"

### ISSUE THREAD

**Issue by PaulYuanJ** [robocorp/rcc#50]
Dears, 

I have build some pre-build envs, when I export them and import them into other mechines by using rcc ht import, a suggestion to make  a progress bar to make it o11y.

refer to:
"github.com/schollz/progressbar/v3"

Why I suggest this?
I have made a platform myself to use rcc tool to manage my RPA robots and environments.
Tt costs lots times to handle holotree import pre-build envs when run the command, it just like "stuck" there, When a user import pre-build env and wait for a long time,  a lot of questions will come, "what happend now?" "How should I do?" "If it is stuck"

I think you may have a better solution to optimize it.

Thank you very much.

**Comment by PaulYuanJ** [comment]
I have tried to make it observability:

`operations/progressbar.go`
```golang
package operations

import (
	"fmt"
	"os"
	"time"

	progressbar "github.com/schollz/progressbar/v3"
)

func NewCountProgressBar(length int64, description string) *progressbar.ProgressBar {
	return progressbar.NewOptions64(
		int64(length),
		progressbar.OptionSetWriter(os.Stderr),
		progressbar.OptionShowIts(),
		progressbar.OptionUseANSICodes(true),
		progressbar.OptionSetDescription(fmt.Sprintf("%s", description)),
		progressbar.OptionSetWriter(os.Stderr),
		progressbar.OptionShowCount(),
		progressbar.OptionSetWidth(10),
		progressbar.OptionThrottle(65*time.Millisecond),
		progressbar.OptionShowCount(),
		progressbar.OptionOnCompletion(func() {
			fmt.Fprint(os.Stderr, "\n")
		}),
		progressbar.OptionSpinnerType(14),
		progressbar.OptionFullWidth(),
		progressbar.OptionSetRenderBlankState(true),
	)
}

```

and use this progressbar in 
`operations/zipper.go` like this

```golang
...
	length := len(it.reader.File)

	bar := NewCountProgressBar(int64(length), "Extracting")

	for _, entry := range it.reader.File {
		bar.Add(1)
		if entry.FileInfo().IsDir() {
			continue
		}
		target := filepath.Join(directory, slashed(entry.Name)[limit:])
		todo := WriteTarget{
			Source: entry,
			Target: target,
		}
		err := todo.execute()
		if err != nil {
			return fmt.Errorf("Problem while extracting zip, reason: %v", err)
		}
	}
...
```

when I run the command, the progressbar shows and it let me know the real progress:

![image](https://github.com/robocorp/rcc/assets/32631327/a87d017d-26ef-41f9-b2a3-74244b220416)

**Comment by vjmp** [comment]
@PaulYuanJ 
Since you now have solution, I'll recommend that we close this issues. And unfortunately that solution does not work for our use cases, so for now, I won't be implementing it in this code base.

**Comment by PaulYuanJ** [comment]
Sure, please kindly close this ticket, thank you~
