### ISSUE TITLE
Handling of .py files in pre-run scripts is unreliable on Windows.

### ISSUE THREAD

**Issue by fabioz** [robocorp/rcc#51]
It seems a few places (including templates) reference using pre-run scripts as:

```
preRunScripts:
  - generate-workitem-file.py output/random-workitem-file.txt
```

With a shebang of `#! /usr/bin/env python`

Now, on Windows this will plainly ignore the shebang and will do whatever the system is instructed to do. In my case when running in VSCode the error I had was:

> Script 'generate-workitem-file.py output/random-workitem-file.txt' failure: fork/exec X:\robocorpws\vscode-robot-tests\ExamplePreRun\bin\generate-workitem-file.py: %! (MISSING)is not a valid Win32 application.

And when running out of VSCode it opened it in an editor.

For Raivo, it did work on its machine (so, it depends on how the system is configured).

So, the suggestion is that this wouldn't be system dependent and when a `.py` file is executed the command would be automatically changed to:
1. Prepend `python`
2. Search the PATH for the `.py` file and use the full path (to be compatible with what's currently done by the shell).

**Comment by cmin764** [comment]
Meanwhile, I added the following fixes right in the robot logic:
- [template-extended-producer-consumer](https://github.com/robocorp/template-extended-producer-consumer/commit/f7f92321410ff7e0af7a0abe346251b4edf65daa)
- [example-private-pypi](https://github.com/robocorp/example-private-pypi/commit/ddcf04a2e1ed06d20d4471f929c5cd4d0c88e645)

**Comment by vjmp** [comment]
I think correct way here is to have correct invocation entries in `robot.yaml` (both pre-run scripts and actual robot scripts) and not make `rcc` to guess what developer intention with their command are.

So for now, I would say that there are two things to be done:

1. in templates use full commands (python, ruby, perl, bash, zsh, ...) that can be found from PATH (inside environment)
2. also in example robots, apply same strategy

And if no objections, I'll close this issue in near future. @cmin764 @fabioz @kariharju

**Comment by cmin764** [comment]
I agree with explicit being better than implicit and already adopted this mindset. As long as you execute scripts starting with the **binary** (which is found in PATH), instead of relying on extension magic and executable header, everything should run stable without guessing.
