### ISSUE TITLE
Remove dependency from English language on Windows by using SID instead of group name

### ISSUE THREAD

**Issue by simonmeggle** [robocorp/rcc#54]
I am experiencing problems with RCC on a german Windows system. 
The command 

    rcc holotree shared --enable

returns with an error: 

![image](https://github.com/robocorp/rcc/assets/1897410/a86a693f-3c1f-42bb-8e0e-7b43aaf81080)

This is because the localized Windows versions have other names for the group "Users" (in Germany:  "Benutzer"). 

A way to solve such localization issues is to avoid names of users and groups and **use their SID instead**. 
(https://learn.microsoft.com/en-US/windows-server/identity/ad-ds/manage/understand-security-identifiers)

Therefore, I request to change the command in `cmd/command_windows.go` to 

    icacls C:\ProgramData\robocorp /grant "*S-1-5-32-545:(OI)(CI)M" /T /Q

which has exactly the same effect.

Thanks and regards :wave: 
Simon

**Comment by simonmeggle** [comment]
I have a Robotmk field test this afternoon with a customer who has a German Windows installed. For this we compiled RCC with this wellknown-SID patch. 
I will report if everything worked!

**Comment by simonmeggle** [comment]
@kariharju The patched version of RCC with the SID worked as expected :+1: 
Shall we submit a PR?

**Comment by vjmp** [comment]
PR taken manually. This is in rcc v17.15.0. Added needed changelog and version info.
