### ISSUE TITLE
Add NO_PROXY setting to RCC profile 

### ISSUE THREAD

**Issue by simonmeggle** [robocorp/rcc#57]
RCC profiles allow me to set `http_proxy`  and `https_proxy`  variables which are used then during installation (to fetch sources) and during execution.

However, the libraries handle these two proxy variables very differently.
Some respect them - Playwright on the other hand has to be configured separately to talk to a proxy. (during import, or via commandline argument).
However, `http_proxy` and `https_proxy` also affect the internal communication from Python to the Playwright process.
In this case there is this error:

    failed: Could not connect to the playwright process at port 64346.

See also https://github.com/MarketSquare/robotframework-browser/issues/1037

You can fix this with another env variable `NO_PROXY=localhost,127.0.0.1`

If I understand correctly, this third - very important - proxy option NO_PROXY should be added to RCC profiles. 
Only then the internal HTTP communication with the Playwright process via localhost is still successful even when a proxy is configured.

**Comment by vjmp** [comment]
Note: Functionality is now in rcc. But Setup Utility (editing) support is coming sometimes later.
